const GEOCACHE_ATTRIBUTE_LABELS: Readonly<Record<string, string>> = {
  "1": "Dogs",
  "2": "Access or parking fee",
  "3": "Climbing gear required",
  "4": "Boat required",
  "5": "Scuba gear required",
  "6": "Recommended for kids",
  "7": "Takes less than one hour",
  "8": "Scenic view",
  "9": "Significant hike",
  "10": "Difficult climb",
  "11": "May require wading",
  "12": "May require swimming",
  "13": "Available 24/7",
  "14": "Recommended at night",
  "15": "Available in winter",
  "16": "Cactus",
  "17": "Poisonous plants",
  "18": "Dangerous animals",
  "19": "Ticks",
  "20": "Abandoned mine",
  "21": "Cliffs or falling rocks",
  "22": "Hunting area",
  "23": "Dangerous area",
  "24": "Wheelchair accessible",
  "25": "Parking nearby",
  "26": "Public transportation nearby",
  "27": "Drinking water nearby",
  "28": "Public restrooms nearby",
  "29": "Telephone nearby",
  "30": "Picnic tables nearby",
  "31": "Camping nearby",
  "32": "Bicycles",
  "33": "Motorcycles",
  "34": "Quads",
  "35": "Off-road vehicles",
  "36": "Snowmobiles",
  "37": "Horses",
  "38": "Campfires",
  "39": "Thorns",
  "40": "Stealth required",
  "41": "Stroller accessible",
  "42": "Owner attention requested",
  "43": "Livestock nearby",
  "44": "Flashlight required",
  "45": "Lost and Found tour",
  "46": "Trucks or RVs",
  "47": "Field puzzle",
  "48": "UV light required",
  "49": "May require snowshoes",
  "50": "May require cross country skis",
  "51": "Special tool required",
  "52": "Night cache",
  "53": "Park and grab",
  "54": "Abandoned structure",
  "55": "Short hike under 1 km",
  "56": "Medium hike between 1 km and 10 km",
  "57": "Long hike over 10 km",
  "58": "Fuel nearby",
  "59": "Food nearby",
  "60": "Wireless beacon",
  "61": "Partnership cache",
  "62": "Seasonal access",
  "63": "Recommended for tourists",
  "64": "Tree climbing required",
  "65": "Yard at a private residence",
  "66": "Teamwork cache",
  "67": "GeoTour",
  "69": "Bonus cache",
  "70": "Power trail",
  "71": "Challenge cache",
  "72": "Geocaching.com solution checker"
};

export function geocacheAttributeLabel(id: string) {
  return GEOCACHE_ATTRIBUTE_LABELS[id];
}
